const assert = require('node:assert/strict');
const { goal, evolution, project } = require('./calculator.js');
const row = (mention, credits = 4, semester = 1) => ({ name: 'Disciplina', credits, semester, mention, module: 'integrante' });
const near = (actual, expected) => assert.ok(Math.abs(actual - expected) < 1e-10, `${actual} != ${expected}`);
const sample = [row('MS', 4, 1), row('CURSANDO', 2, 2), row('CURSANDO', 4, 2)];
const unchanged = JSON.stringify(sample);
const target = goal(sample, 4.5);
near(target.required, 14 / 3); near(target.maximum, 4.75);
assert.equal(target.status, 'achievable'); assert.ok(project(sample, target.example).projected.ira >= 4.5);
assert.equal(goal(sample, 5).status, 'impossible');
assert.equal(goal(sample, 1).required, 0);
assert.equal(goal([], 4).status, 'no_ongoing');
assert.equal(goal([row('SS')], 5).status, 'no_ongoing');
near(goal([row('CURSANDO')], 4.5).required, 4.5);
const capped = goal([row('SS', 4, 6), row('CURSANDO', 4, 20)], 4);
near(capped.required, 3); near(capped.maximum, 5);
assert.equal(goal(sample, 4.75).status, 'achievable');
for (const invalid of [-1, 6, NaN, null, '4.5']) assert.throws(() => goal(sample, invalid));
assert.equal(JSON.stringify(sample), unchanged);
const history = evolution([row('MS', 4, 8), row('SS', 6, 1), row('SR', 2, 2), row('CC', 4, 3), row('CURSANDO', 4, 9)]);
assert.deepEqual(history.map(point => point.semester), [1, 2, 8]);
near(history[0].ira, 5); near(history[1].ira, 3); near(history[2].ira, 126 / 34);
assert.equal(history[1].count, 1); assert.equal(history[1].credits, 2);
assert.deepEqual(evolution([row('CC'), row('TR'), row('CURSANDO')]), []);
near(evolution([row('SR')])[0].ira, 0);
console.log('Meta e evolução aprovadas: média exigida, limites, exemplos realizáveis, semestre limitado a 6, ordem cronológica, exclusões, SR e preservação do histórico.');
