const assert = require('node:assert/strict');
const { project } = require('./calculator.js');
const row = (mention, credits = 4, semester = 1, module = 'integrante') => ({ name: 'Disciplina', mention, credits, semester, module });
const near = (actual, expected) => assert.ok(Math.abs(actual - expected) < 1e-12, `${actual} != ${expected}`);
const rows = [row('SS', 4, 1), row('CURSANDO', 4, 2), row('CURSANDO', 2, 2, 'livre')];
const before = JSON.stringify(rows);
const result = project(rows, [null, 'MM', 'MS']);
near(result.current.ira, 5); near(result.projected.ira, 3.75); near(result.projected.mp, 4);
near(result.delta, -1.25); assert.equal(result.ongoingCount, 2);
assert.equal(JSON.stringify(rows), before);
assert.equal(project(rows, [null, 'SS']).projected, null);
assert.equal(project([row('SS')]).projected, null);
assert.equal(project([]).projected, null);
const first = project([row('CURSANDO')], ['SR']);
assert.equal(first.current.ira, null); assert.equal(first.projected.ira, 0); assert.equal(first.delta, null);
near(project([row('SS', 4, 6), row('CURSANDO', 4, 20)], [null, 'SR']).projected.ira, 2.5);
const excluded = project([row('CC'), row('TR'), row('TJ'), row('CURSANDO')], [null, null, null, 'MS']);
near(excluded.projected.ira, 4); assert.equal(excluded.current.ira, null);
for (const grade of ['CC', 'TR', 'BAD', 5]) assert.throws(() => project([row('CURSANDO')], [grade]));
assert.throws(() => project(rows, {}));
assert.throws(() => project([row('CURSANDO', 0)], ['SS']));
console.log('IRA projetado aprovado: pesos, semestre limitado a 6, módulo livre, SR, exclusões, histórico vazio, seleção incompleta e preservação das menções reais.');
